communicator:
  verbose: False
debug:
  debug_mode: False
  validation_mode: False
encoder:
  precision_bits: 16
  trunc_method:
    # prod: "crypten"
    prod: "egk"
    # lut: "crypten"
    lut: "egk"
functions:
  max_method: "log_reduction"

  exp:
    method: "limit"
    iterations: 8
    haar_size_bits: 5
    bior_size_bits: 5
    lut_max_bits: 6
    all_neg: True
    neg_lut_size: 256 # 2^8

  log:
    method: "bior"
    iterations: 2
    exp_iterations: 8
    order: 8
    haar_size_bits: 8
    bior_size_bits: 8
    lut_max_bits: 6

  reciprocal:
    method: "bior"
    nr_iters: 10
    log_iters: 1
    all_pos: True
    initial: null
    haar_size_bits: 8
    bior_size_bits: 7
    lut_max_bits: 6

  sqrt:
    method: "bior"
    nr_iters: 3
    nr_initial: null
    haar_size_bits: 6
    bior_size_bits: 6
    lut_max_bits: 6

  inv_sqrt:
    method: "bior" # "haar"
    haar_size_bits: 16
    bior_size_bits: 16
    lut_max_bits: 1
    tailored_0_lut_max_bits: 0
    tailored_0_haar_size_bits: 12
    tailored_1_lut_max_bits: 8
    tailored_1_haar_size_bits: 8

  sigmoid_tanh:
    method: "bior" # "bior-lut-only"
    terms: 32
    haar_size_bits: 8
    bior_size_bits: 8
    sigmoid_lut_max_bits: 6
    tanh_lut_max_bits: 5

  trigonometry:
    method: "bior"
    haar_size_bits: 8
    bior_size_bits: 8
    lut_max_bits: 5
    iterations: 10

  erf:
    method: "bior"
    iterations: 8
    haar_size_bits: 8
    bior_size_bits: 8
    lut_max_bits: 5

  gelu:
    method: "bior-lut-only"
    haar_size_bits: 4
    bior_size_bits: 4
    lut_max_bits: 2

  silu:
    method: "bior-lut-only"
    haar_size_bits: 4
    bior_size_bits: 4
    lut_max_bits: 4
mpc:
  active_security: False
  provider: "TTP"
  protocol: "beaver"
nn:
  dpsmpc:
    protocol: "layer_estimation"
    skip_loss_forward: True
    cache_pred_size: True
